### ISSUE TITLE
Prevent spamming of task

### ISSUE THREAD

**Issue by espinm2** [graphics-rpi/oasis#12]
### Problem

Right now we handle task in a first come first server manner. This works well for low volume traffic. But we do not know how this would react to high volume traffic. If a user spams 100s of task just to clog our server, we would have to process all of those task before moving on other task. This will lead to other users having long wait times.
### Solution

Modify the code we use inside of `/var/www/bin/process_scripts` to handle this case. Suggestions include detection of user (given inside the task file as a hashed entry) and some rules in place to avoid processing a specific users task more than N number of times in a row. 
### TODO
- [ ] research the method used to handle this case
- [ ] implement this method
- [ ] test by running two users at the same time and spamming the server with one user, and trying to regularly use the server with another.
